[package]
name = "hazel-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
file-format = "0.15"
chrono = "0.4"
notify = { version = "5.1", features = ["serde"] } 
regex = "1.7"
snafu = "0.7"
pest = "2.5"
pest_derive = "2.5"
mime_guess = "2.0"
fs_extra = "1.3"
