[package]
name = "hazel-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4"
notify = { version = "5.1", features = ["serde"] } 
regex = "1.7"
snafu = "0.7"
infer = "0.3"
pest = "2.5"
pest_derive = "2.5.6"
