token     = { ^"year" | ^"month" | ^"mime" | ^"extension" }
specifier = { ^"created" | ^"modified" | ^"accessed" }
modifier  = { ^"lowercase" | ^"uppercase" | ^"names" }
variable  = { "{"{,1} ~ token ~ ":"? ~ specifier? ~ ":"? ~ (modifier ~ "|"? ~ modifier?)*? ~ "}"{,1} }
text      = { (ASCII_ALPHANUMERIC ~ (" " | "_" | "!" | "." | "-" | "~" | "@")?)+ }
path      = { ("/"{,1}? ~ (variable | text) ~ "/"{,1}?)+ }
